const routes = {
  path: '/system-mgt',
  name: 'system-mgt',
  remark: '系统管理',
  authority: 'sm',
  routes: [
    // {
    //   path: '/system-mgt/organization-mgt',
    //   name: 'system-mgt-organization-mgt',
    //   component: './system-mgt/organization-mgt',
    //   icon: 'setting',
    //   // authority: '08-01',
    //   remark: '单位管理',
    // },
    {
      path: '/system-mgt/UnitManagement',
      name: 'system-mgt-organization-mgt',
      component: './system-mgt/UnitManagement',
      icon: 'setting',
      remark: '组织管理',
      authority: 'sm/um',
    },
    {
      path: '/system-mgt/user-mgt',
      name: 'system-mgt-user-mgt',
      component: './system-mgt/user-mgt',
      icon: 'setting',
      remark: '用户管理',
      authority: 'sm/um',
    },
    {
      path: '/system-mgt/role-mgt',
      name: 'system-mgt-role-mgt',
      component: './system-mgt/role-mgt',
      icon: 'setting',
      remark: '角色管理',
      // authority: 'sm-rm',
    },
    {
      path: '/system-mgt/authority-mgt',
      name: 'system-mgt-authority-mgt',
      component: './system-mgt/authority-mgt',
      icon: 'setting',
      remark: '权限管理',
      // authority: 'sm-am',
    },
    {
      path: '/system-mgt/dictionary-mgt',
      name: 'system-mgt-dictionary-mgt',
      component: './system-mgt/dictionary-mgt',
      icon: 'setting',
      remark: '字典管理',
    },
    {
      path: '/system-mgt/log-audit',
      name: 'system-mgt-log-audit',
      component: './system-mgt/log-audit',
      icon: 'setting',
      remark: '日志审计',
    },
    {
      path: '/system-mgt/keyword-mgt',
      name: 'system-mgt-keyword-mgt',
      component: './system-mgt/keyword-mgt',
      icon: 'setting',
      remark: '词库管理',
      // authority: 'sm-km',
    },
    {
      path: '/system-mgt/unread-msg',
      name: 'system-mgt-unread-msg',
      component: './system-mgt/unread-msg',
      icon: 'setting',
      remark: '未读消息',
    },
    {
      path: '/system-mgt',
      redirect: '/system-mgt/organization-mgt',
      hideInMenu: true,
    },
  ],
};

export default routes;
